# kubeconfig
apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://192.168.49.2:8443
    certificate-authority-data: MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
a3ViZUNBMB4XDTI0MDQyMjE2MTI1OVoXDTM0MDQyMTE2MTI1OVowFTETMBEGA1UE
AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALP9
BQpPImoQMEky5bF+xSa3nplSZ1OnA9rq0xnhynIG3o9jm0oBnu9TN72K6aMOujrx
3xYQLEoycVSzAIYZfrOus6Cl1ljZQkcAT/xp3Lu40BCHTKd7IsmJT6h6B3wqlsXe
wH5hFu7vvg2sK5x8354UNtjcY31v61rGWMi+658Pz6rJb1Q+0rjt915QC1k8Se2a
WlmNpxuq8hYXAB/Xh1tb4kCvymAphWS0sGmE802UNQ8yim5+MrenXSmJiK+xM3+D
caXCsi8PGWF3Rzha6ygcznaipP0oCH89rm5A8Nlw6OB86tsFj36y4rymWg2dtRT4
R65szbY8wT2M3Lr0dC8CAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
BBSwuAn7Bd8TsGMT1v3yN+kUwvX9NzANBgkqhkiG9w0BAQsFAAOCAQEASeR5GPPN
qIu6n1v2Bpl/OJrnC1kK3NpIfpP1SUQhNWVmIZKSIL7J06hcnmA1Wgr8ogFsbCpZ
JkRgqY9T8c8/q2QYXXRKvsycOT6vuxEeDzL7uOMcvTtK7HjZm949XROnKqi4S4Pp
XLi7Uw1g6+wbq+MmZpT6p6vvso3vUou/jXeQsiw6lmJVFOMP3pPS8EkEH939bWh2
Y74w3F1PJAxOZWZ5b2RsEXY7VVRgBQCpiNSvHIODBsC8YSExqmdzO7SVymo6lv5H
mMeSzbseIooBayB9lmJcJXbsOPjG72D+R9i/84MZXcXEEUu8NM5rCl5+eJ9wKHqP
qdQAiVw+gpZTEQ==
  name: your-cluster
contexts:
- context:
    cluster: your-cluster
    user: github-actions
  name: github-actions
current-context: github-actions
users:
- name: github-actions
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ik1BNEZkTm9sQ1FQdC1KRGRtT2ZsV3BjQnZJZ0tkcHdxNEJsV3BVQ0NIamsifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImdpdGh1Yi1hY3Rpb25zLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImdpdGh1Yi1hY3Rpb25zIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNjhhZjY5ODItYjhjYy00ZTU2LTljODQtMjYyYzczNmY5OGM1Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6Z2l0aHViLWFjdGlvbnMifQ.p-zOLo0P6gEIUtUfe73qhbjol2j8unTRkFKpqXisFkId4fWLwP78yt7ZUGF5AizGtvkoF1e9AX1Z8J6n_x6Fgewg4wfO4RZSvx8PdCmgxvBS0AjUEcImQzZn5xqqyUO7PvUioqokpCVIlbXJNz3vxhlbrUTjjPBMH3GLPoVKp4XCzm6KDYC5ukvRDXQMOzemyhQUWpBxo8x5G7YjYpip3KjKENVGdKOIsTJ05fduScFt2bhECBwmGoCNwFn9ot0LvUjVifPtJf6ifWd1ed9wYBUcFMXeKHI50L04_2Egg3Tgy_6f8iOavJAJlHxnCiWmeLmtSVKgYE8h6S2xGA8pQQ
