name: Deploy WeatherApp

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to DockerHub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: strukovsergei
        password: ${{ secrets.DOCKERHUN_TOKEN }} 
        
    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t strukovsergei/weatherapp:latest .
        docker tag strukovsergei/weatherapp:latest strukovsergei/weatherapp:${{ github.sha }}

    # Push Docker image to DockerHub
    - name: Push Docker image to DockerHub
      run: |
        docker push strukovsergei/weatherapp:${{ github.sha }}

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
              
    steps:
    # Checkout the Kubernetes manifest repository
    - name: Setup yq
      uses: vegardit/gha-setup-yq@v1
    
    - name: Checkout Kubernetes manifest repository
      uses: actions/checkout@v3
      with:
        repository: strukovsergei/weatherapp-k8s
        token: ${{ secrets.ACTIONS_TOKEN }}
        path: weatherapp-k8s

        
    # Update the Kubernetes deployment manifest
    - name: Update Kubernetes deployment manifest
      run: |
        # Replace the image tag in the Kubernetes deployment manifest
        yq eval '.spec.template.spec.containers[0].image = "strukovsergei/weatherapp:${{ github.sha }}"' -i weatherapp-k8s/deployment.yaml

    # Commit and push changes
    - name: Commit and push changes
      run: |
        cd weatherapp-k8s
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add deployment.yaml 
        git commit -m "Update image to weatherapp:${{ github.sha }}"
        git push origin main
